stan-core:
  excludes:
    - '*.local'
    - assets/**
    - CHANGELOG.md
    - docs/**
    - package-lock.json
  imports:
    entity-tools:
      - ../entity-tools/.stan/system/stan.requirements.md
      - ../entity-tools/.stan/system/stan.todo.md
      - ../entity-tools/dist/index.d.ts
      - ../entity-tools/.stan/interop/mock-db/**
  stanPath: .stan
stan-cli:
  cliDefaults:
    run:
      facets: true
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint: npm run lint:fix
    test: npm run test -- --no-color
    build:
      script: cross-env NO_COLOR=1 npm run build
      warnPattern: ^(?!.*outputToFilesystem option is defaulting to true)\\(\\!\\) \\[plugin typescript\\].*
    docs:
      script: npm run docs -- --emit none
      warnPattern: \\[warning\\]
    knip: npm run knip

